addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: be26ad43-f6ea-479c-acd0-e8060a64c721
jdk: [oraclejdk8]
language: java
script: [mvn install, ./df-build.sh]
sudo: 'false'
# Modified by Insights Service at 2016-04-08 15:00:57.911115
